Makefile

Allow installing the CRDs on a cluster with `make`.

Add make install and uninstall targets

---

.gitignore
api/v1alpha1/application_types.go
api/v1alpha1/component_types.go
api/v1alpha1/componentdetectionquery_types.go
config/crd/bases/appstudio.redhat.com_applications.yaml
config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
config/crd/bases/appstudio.redhat.com_components.yaml
config/kcp/apiexport.yaml
config/kcp/apiresourceschema.yaml
manifests/application-api-customresourcedefinitions.yaml

For issue: https://issues.redhat.com/browse/DEVHAS-49
This PR adds additional printer columns to component/application/cdq 's GET output
added latest condition fields - `status`, `reason`, and `type` (specifically for cdq, since cdq has in-progress and complete status) to the CRDs
for component & application:
```
$ kubectl get hc
NAME                      AGE    STATUS   REASON
devfile-sample-go-basic   111s   True     OK
$ kubectl get ha
NAME                 AGE   STATUS   REASON
application-sample   17s   True     OK
```
failure case: 
```
$ kubectl get hc
NAME                      AGE   STATUS   REASON
devfile-sample-go-basic   8s    False    Error
```
For CDQ, in-progress & complete:
```
$ kubectl get hcdq
NAME                              AGE     STATUS   REASON    TYPE …
```

[DEVHAS-49]Add additional fields to CRDs get output

---

api/v1alpha1/webhook_suite_test.go

This library is removed in latest controller-runtime so is breaking dependencies in other packages.
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

fix: remove printer libary from webhook test

---

api/v1alpha1/snapshotenvironmentbinding_types.go

Signed-off-by: John Pitman <jpitman@redhat.com>
This PR adds the constants used by SnapshotEnvironmentBindingStatus' ComponentDeploymentCondition's field, so that other teams can use them.
This is part of Jira story https://issues.redhat.com/browse/GITOPSRVCE-346

Add constants for SnapshotEnvironmentBindingStatus' ComponentDeploymentCondition's field

---

PROJECT
api/v1alpha1/snapshot_webhook.go
api/v1alpha1/webhook_suite_test.go
config/webhook/manifests.yaml

**This PR**:
- Adds a new `Snapshot` resource webhook scaffolding via `operator-sdk create webhook`
- The webhook API URL will be handled by the appstudio-controller of GitOps Service. See https://github.com/redhat-appstudio/managed-gitops/pull/289 for this work.
- Fixes old references in the PROJECT file, and adds webhooks
- Regenerates the manifests using `make generate manifests`
A part of JIRA story https://issues.redhat.com/browse/GITOPSRVCE-211

Add initial support for Snapshot validating webhook

---

PROJECT
api/v1alpha1/promotionrun_webhook unit_test.go
api/v1alpha1/promotionrun_webhook.go
api/v1alpha1/snapshot_webhook unit_test.go
api/v1alpha1/snapshot_webhook.go
api/v1alpha1/snapshotenvironmentbinding_webhook unit_test.go
api/v1alpha1/snapshotenvironmentbinding_webhook.go
api/v1alpha1/webhook_suite_test.go
config/webhook/manifests.yaml

This PR is to add webhook for `Snapshot`, `SnapshotEnvironmentBinding` and `PromotionRun` CRs.
Here are the fields monitored by webhook.
**SnapshotEnvironmentBinding**
.metadata.labels
.spec.application 
.spec.environment
**Snapshot**
.spec.application
.spec.components
**ApplicationPromotionRun**
.spec
https://issues.redhat.com/browse/GITOPSRVCE-211

Add Webhooks for CRs to avoid modifications in immutable fields.

---

api/v1alpha1/environment_types.go
config/crd/bases/appstudio.redhat.com_environments.yaml
manifests/application-api-customresourcedefinitions.yaml

Environment's .spec.Type field is  optional so added omitempty to this field
JIRA ticket - https://issues.redhat.com/browse/GITOPSRVCE-356

Add omitempty to Type field of Environment spec

---

api/v1alpha1/application_webhook.go
api/v1alpha1/application_webhook_test.go
api/v1alpha1/component_webhook.go
api/v1alpha1/component_webhook_test.go
api/v1alpha1/component_webhook_unit_test.go

Fixes https://issues.redhat.com/browse/DEVHAS-241
Updates the webhook validation for Application and Component CR names to ensure they conform to the DNS-1053 specification.

[DEVHAS-241] Require Application and Component names to conform to DNS-1053

---

.github/workflows/pr.yaml

Since we have paused supporting KCP, we can disable the workflow job for installing KCP.

Remove workflow job to install KCP tooling

---

api/v1alpha1/snapshotenvironmentbinding_types.go
config/crd/bases/appstudio.redhat.com_snapshotenvironmentbindings.yaml
manifests/application-api-customresourcedefinitions.yaml

See GITOPSRVCE-199
FYI: @jgwest
Notes to reviewer: 
- ran make targets: build, fmt, lint, generate, manifests
- feel free to change comments to your liking
- Did not run target: manifests-kcp

GitOps: Add sync/health/commitID to Snapshot Env Binding (#199)

---

api/v1alpha1/snapshotenvironmentbinding_webhook unit_test.go
api/v1alpha1/snapshotenvironmentbinding_webhook.go

This PR is to remove webhook validation for SnapshotEnvironmentBinding labels as it is not needed anymore.

Remove SnapshotEnvironmentBinding validation for labels.

---

.tekton/push.yaml

Switching to new bundle since development of old one was stopped before attempt to migrate to kcp. New bundle is removing dependency on shared secret.

STONEBLD-777 - tekton-ci: update bundle

---

api/v1alpha1/component_types.go
config/crd/bases/appstudio.redhat.com_componentdetectionqueries.yaml
config/crd/bases/appstudio.redhat.com_components.yaml
manifests/application-api-customresourcedefinitions.yaml

Update API docs to make it clear that we are expecting an HTTPS URL
https://issues.redhat.com/browse/DEVHAS-180

[DEVHAS-180] update gitsource URL description

---

api/v1alpha1/component_webhook.go
api/v1alpha1/component_webhook_test.go
api/v1alpha1/component_webhook_unit_test.go
api/v1alpha1/messages.go
license_header.txt

https://issues.redhat.com/browse/DEVHAS-180
- Existing validation ensures only absolute URLs are accepted.  Modified the error message so it's more user friendly
- Added validation  to ensure URL is coming from github.com
- Refactored error messages from the component controller webhook to a separate `messages.go` file for externalization
- Update license year in header file

[DEVHAS-180] validate gitsource URLs

---

api/v1alpha1/deploymenttargetclaim_types.go

Add constants for annotations and finalizers which can be reused between components.

Add annotation and finalizer constants for DeploymentTargetClaim API

---

api/v1alpha1/deploymenttarget_types.go
config/crd/bases/appstudio.redhat.com_deploymenttargets.yaml
manifests/application-api-customresourcedefinitions.yaml

* Services can skip TLS verification when connecting to this target
* This value will be mapped to the `allowInsecureSkipTLSVerify` field of GitOpsDeploymentManagedEnvironment

Add skip TLS verify field to DeploymentTarget cluster credentials

---

api/v1alpha1/environment_types.go
config/crd/bases/appstudio.redhat.com_environments.yaml
manifests/application-api-customresourcedefinitions.yaml

As discussed on [RHTAP-129/STONE-264](https://docs.google.com/document/d/1ihFNBy3FsW3R3Jyt9zLAM6TpIGYH2tkFmFZTiD2rsBw/edit#heading=h.5o6ujoz34zty) we need a field to describe whether the target K8s environment is Kubernetes or OpenShift. 
This is a first stab at such a field, feel free to provide comments on the PR.

Add type field to Environment configuration, indicating Kubernetes vs OpenShift

---

api/v1alpha1/promotionrun_webhook.go
api/v1alpha1/snapshot_webhook unit_test.go
api/v1alpha1/snapshot_webhook.go
api/v1alpha1/snapshotenvironmentbinding_webhook unit_test.go
api/v1alpha1/snapshotenvironmentbinding_webhook.go

I'm seeing this monstrosity (:grin:) in the appliction controller webhook logs:
`
2023-04-25T19:44:06.265001341Z	INFO	snapshotenvironmentbinding-resource	validate update	{"controllerKind": "SnapshotEnvironmentBinding", "name": "tekton-test-development-binding-vb9wz", "namespace": "rhn-support-rravi-tenant", "controllerKind": "SnapshotEnvironmentBinding", "name": "tekton-test-development-binding-vb9wz", "namespace": "rhn-support-rravi-tenant", "controllerKind": "SnapshotEnvironmentBinding", "name": "tekton-test-development-binding-vb9wz", "namespace": "rhn-support-rravi-tenant", "controllerKind": "SnapshotEnvironmentBinding", "name": "test-app-168233416-development-binding-5w9zl", "namespace": "skhileri-tenant", "controllerKind": "SnapshotEnvironmentBinding", "name": …

Fix excessive Environment API log key/values in webhook logs

---

api/v1alpha1/application_webhook.go
api/v1alpha1/component_webhook.go
api/v1alpha1/environment_webhook.go

The log statements from the webhook code currently look like this, due to use of a global mutable variable:
`
{"level":"info","ts":"2023-06-02T11:57:24.502877274Z","logger":"environment-resource","caller":"v1alpha1/environment_webhook.go:71","msg":"validating the update request","controllerKind":"Environment","name":"development","namespace":"e2e-demos-mitl-tenant","controllerKind":"Environment","name":"development","namespace":"e2e-demos-mitl-tenant","controllerKind":"Environment","name":"development","namespace":"spi-demos-iyei-tenant","controllerKind":"Environment","name":"development","namespace":"byoc-igsk-tenant","controllerKind":"Environment","name":"development","namespace":"spi-demos-xpei-tenant","controllerKind":"Environment","name":"development","namespace":"chains-e2e-dgpf-tena …

Avoid appending the same log keys over and over in webhooks

---

api/v1alpha1/snapshotenvironmentbinding_webhook.go
api/v1alpha1/snapshotenvironmentbinding_webhook_test.go
api/v1alpha1/webhook_suite_test.go
config/webhook/manifests.yaml

I hit issues when trying to setup the new SnapshotEnvironmentBinding webhook code in `appstudio-controller` component, in managed-gitops:
- When trying to call `SetupWebhookWithManager` from appstudio-controller, this error message occurs: `(&applicationv1alpha1.SnapshotEnvironmentBinding{}).SetupWebhookWithManager undefined (type *"github.com/redhat-appstudio/application-api/api/v1alpha1".SnapshotEnvironmentBinding has no field or method SetupWebhookWithManager)`
- Instead, I've tweaked the `SnapshotEnvironmentBinding` webhook code to use a k8s client at package scope.

Use package-scoped client from manager for SnapshotEnvBinding webhook

---

api/v1alpha1/snapshotenvironmentbinding_webhook.go
api/v1alpha1/snapshotenvironmentbinding_webhook_test.go

The most recent update to the SnapshotEnvironmentBinding (SEB) webhook causes update of SnapshotEnvironmentBindings to fail, due to SEB update algorithm matching on itself when looking for duplicates.

SnapshotEnvironmentBinding webhook should not reject updates to existing object

---

api/v1alpha1/environment_webhook.go
api/v1alpha1/environment_webhook_unit_test.go
api/v1alpha1/messages.go

Updated `validateIngressDomain` name to `validateEnvironment` to make it a common function

Add webhook validation for Environment API URL

---

api/v1alpha1/environment_types.go
config/crd/bases/appstudio.redhat.com_environments.yaml
manifests/application-api-customresourcedefinitions.yaml

This PR adds `omitempty` to the `EnvironmentConfiguration.Env` field for the Environment CR. Env being a required field was raised on slack by @skabashnyuk, and I see no reason for it to be required?
CC @maysunfaisal @jgwest for awareness, in case there's a reason it's required.
See more: https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1696254156547549

Add omitempty to EnvironmentConfiguration.env

---

.github/workflows/pr.yaml
.tekton/push.yaml
Makefile
PROJECT
go.mod

Updates the references to `redhat-appstudio/application-api` to `konflux-ci/application-api` as part of the DEVHAS-604 epic.
https://issues.redhat.com/browse/DEVHAS-657

Update application-api references
